"""Predict plans with trusted locally generated DSZ artifacts; preserve provenance."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import joblib  # noqa: E402
import pandas as pd  # noqa: E402

from src.dsz_model import CATEGORICAL, NUMERIC, predict_plans, sha256  # noqa: E402


def predict_from_artifacts(artifact_dir: Path, plans: pd.DataFrame) -> pd.DataFrame:
    """Only call on this pipeline's trusted local files, never uploaded pickle files."""
    manifest = json.loads((artifact_dir / "dsz_model_metrics.json").read_text(encoding="utf-8"))
    if manifest["status"] != "completed":
        raise ValueError("Training run is not completed")
    for name in ["src/dsz_model.py", "scripts/predict_dsz.py"]:
        if manifest.get("source_sha256", {}).get(name) != sha256(ROOT / name):
            raise ValueError(f"Current prediction source differs from training run: {name}")
    predictions = []
    for target, record in manifest["targets"].items():
        if record["status"] != "completed":
            continue
        path = artifact_dir / record["artifact_file"]
        if path.resolve().parent != artifact_dir.resolve() or sha256(path) != record["artifact_sha256"]:
            raise ValueError("Generated model artifact path/SHA differs from manifest")
        bundle = joblib.load(path)
        for key in ["data_kind", "target_assumption", "target_period_confirmed", "source_manifest_sha256"]:
            if bundle[key] != manifest[key]:
                raise ValueError("Model/provenance mismatch")
        if bundle["target"] != target:
            raise ValueError("Artifact target mismatch")
        predictions.append(predict_plans(bundle, plans))
    if not predictions:
        raise ValueError("No trained targets")
    return pd.concat(predictions, ignore_index=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", type=Path, required=True, help="Trusted artifacts generated by train_dsz.py")
    parser.add_argument("--plans", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    plans = pd.read_csv(args.plans, encoding="utf-8-sig", keep_default_na=False,
                        dtype={name: str for name in CATEGORICAL + ["plan_id"]},
                        na_values={name: [""] for name in NUMERIC})
    result = predict_from_artifacts(args.artifact_dir, plans)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(args.output, index=False, encoding="utf-8-sig")
    metadata = {"data_kind": result["data_kind"].unique().tolist(),
                "target_assumption": result["target_assumption"].unique().tolist(),
                "target_period_confirmed": result["target_period_confirmed"].unique().tolist(),
                "training_manifest_sha256": sha256(args.artifact_dir / "dsz_model_metrics.json"),
                "plans_sha256": sha256(args.plans), "prediction_sha256": sha256(args.output),
                "rows": len(result), "interpretation": result["interpretation"].unique().tolist()}
    args.output.with_suffix(".provenance.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(metadata, ensure_ascii=False))
